

export const STUDENT_REGISTER_LOADING="STUDENT_REGISTER_LOADING"
export const STUDENT_REGISTER_SUCCESS="STUDENT_REGISTER_SUCCESS"
export const STUDENT_REGISTER_ERROR="STUDENT_REGISTER_ERROR"

export const STUDENT_LOGIN_LOADING="STUDENT_LOGIN_LOADING"
export const STUDENT_LOGIN_SUCCESS="STUDENT_LOGIN_SUCCESS"
export const STUDENT_LOGIN_ERROR="STUDENT_LOGIN_ERROR"