

export const ADD_LECTURE_LOADING="ADD_LECTURE_LOADING"
export const ADD_LECTURE_SUCCESS="ADD_LECTURE_SUCCESS"
export const ADD_LECTURE_ERROR="ADD_LECTURE_ERROR"

export const GET_LECTURE_LOADING="GET_LECTURE_LOADING"
export const GET_LECTURE_SUCCESS="GET_LECTURE_SUCCESS"
export const GET_LECTURE_ERROR="GET_LECTURE_ERROR"